#!/usr/local/bin/perl
#
################################################################
#
# Filename: nchain 
#
# Description: Displays netgroup chain for the given host
#
# Usage: nchain <hostname>
#
# Author: jadew
#
# Current Maintainer: jadew
#
# Reviewer(s): ??
#
################################################################

use warnings;
use strict;

#declarations
my $host;
my @chain;

if (!($host = $ARGV[0]) or ($ARGV[0] eq "--man") or ($ARGV[0] eq "--help")) {
	print "Usage: nchain <hostname>\n";
	print "\n";
	print "Displays all netgroups the given host is a member of (if any), and the ancestry of each of those netgroups.\n";
	exit;
}

if ($^O eq "linux") {
	print "Must be run on Solaris, does not work on Linux.\n";
	exit;
}

my @groups = `nismatch host=$host.cisco.com netgroup.org_dir`;

if ($#groups == -1) {
	print "$host is not in any netgroups.\n";
	exit;
}

print "$host is in the following netgroup(s):\n";

foreach my $group (@groups) {
	($group) = split(/\s+/,$group);
	unshift(@chain, $group);
	walk_chain();
	shift @chain;
}

sub walk_chain {
	my @groups = `nismatch group=$chain[0] netgroup.org_dir`;
	if ($#groups == -1) {
		print_chain();
		return;
	}

	foreach my $group (@groups) {
		my ($pgroup) = split(/\s+/,$group);
		unshift (@chain,$pgroup);
		walk_chain();
		shift @chain;
	}
}

sub print_chain {
	foreach my $item (@chain) {
		print "$item\n";
	}
	print "\n";
}
